name: Release Build

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"

            - name: Download dependencies
              run: npm ci

            - name: Build LauncherCore
              run: npm run build

            - name: Publish LauncherCore to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
